apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tester-1
  name: tester-1
  labels:
    app: tester-1
spec:
  selector:
    matchLabels:
      app: tester-1
  template:
    metadata:
      labels:
        app: tester-1
        name: tester-1
    spec:
      containers:
        - name: tester-1
          image: sindhutrisha/Tester-1/tester-1
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 8659
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        