apiVersion: v1
kind: Service
metadata:
  namespace: tester-1
  labels:
    app: tester-1
  name: tester-1
spec:
  ports:
  
    - protocol: TCP
      port: 8659
      targetPort: 8659
   
   
  selector:
    app: tester-1
  type: ClusterIP
